"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  type ReactNode,
} from "react";

export type Lang = "en" | "ja" | "zh";

/* ════════════════════════════════════════
   TRANSLATIONS
════════════════════════════════════════ */
export const T = {
  en: {
    nav: {
      home: "Home",
      token: "Token",
      pump: "Pump",
      calculator: "Calculator",
      roadmap: "Roadmap",
      community: "Community",
      events: "Events",
      donation: "Donation",
      docs: "Docs",
      buy: "Buy $KIYOMASA",
    },
    hero: {
      badge: "Live on Solana",
      line1: "JAPAN'S",
      line2: "GORILLA",
      line3: "MEME IS HERE",
      sub: "Inspired by Kiyomasa, Japan's iconic gorilla. A community-driven meme movement built by believers, creators, and degens.",
      buyBtn: "🔥 Buy $KIYOMASA",
      joinBtn: "Join Community 🦍",
      copy: "Copy",
      network: "Network",
      supply: "Supply",
      tax: "Tax",
      community: "Community",
      tapMe: "Tap me!",
      clicks: "clicks",
    },
    token: {
      eyebrow: "On-Chain · Real-Time",
      heading: "Token",
      headingAccent: "Information",
      price: "$KIYOMASA Price",
      marketCap: "Market Cap",
      volume24h: "Volume 24h",
      liquidity: "Liquidity",
      fdv: "FDV",
      buys: "Buys",
      sells: "Sells",
      txTotal: "24h Transactions · {n} total",
      chartLabel: "📈 Real-Time Chart",
      openFull: "Open Full →",
      detailsHeading: "Token Details",
      caHeading: "Contract Address",
      caLabel: "Solana CA",
      copyBtn: "Copy Contract Address",
      copyOk: "✓ Copied!",
      buyJup: "Buy on Jupiter",
      dex: "DexScreener",
      updatedJustNow: "just now",
      updatedAgo: "{n}s ago",
      updated: "Updated",
      live: "Live",
      buyPct: "{n}% buys",
      sellPct: "{n}% sells",
    },
    pump: {
      eyebrow: "Real-Time · On-Chain",
      heading: "Pump",
      headingAccent: "-o-Meter",
      sub: "Composite score of buy pressure, volume, and price momentum. Updates every 30 seconds.",
      score: "PUMP SCORE",
      verdict: "Verdict",
      buy: "Buy",
      sell: "Sell",
      volume: "Volume 24h",
      liquidity: "Liquidity",
      marketCap: "Market Cap",
      price1h: "Price 1h",
      price24h: "Price 24h",
      txns: "Transactions 24h",
      rekt: "REKT 💀",
      bearish: "BEARISH 🐻",
      neutral: "NEUTRAL 😐",
      bullish: "BULLISH 🔥",
      pumping: "PUMPING 🚀",
      moon: "TO THE MOON 🌙",
    },
    calc: {
      eyebrow: "Dream Big · WAGMI",
      heading: "Wen",
      headingAccent: "Moon?",
      sub: "Enter your token amount, pick a target, and see your future.",
      currentPrice: "Current Price",
      token: "Token",
      amountLabel: "How many $KIYOMASA do you hold?",
      placeholder: "e.g. 1000000",
      multLabel: "Target Multiplier",
      custom: "Custom",
      calcBtn: "🔮 Calculate My Moon Bag",
      currentVal: "Current Value",
      targetAt: "At {n}x Target",
      profit: "Your Profit",
      targetPrice: "Target Price",
      targetSub: "{n}x current",
      disclaimer: "Not financial advice. Do your own research. 🦍",
      loading: "Loading…",
      wagmi: [
        "Basically flat 😴 Hold longer bro",
        "Solid. WAGMI 🤝",
        "BASED. You're making it 🔥",
        "MASSIVE BAGS. Future millionaire 🤑",
        "KIYOMASA TO THE MOON!!! 🚀🌙 NGMI if you sell",
      ],
    },
    community: {
      eyebrow: "Gorilla Army",
      heading: "Join The",
      headingAccent: "Movement",
      sub: "The gorilla army grows stronger every day. Pick your channel. Bring the energy.",
      xDesc:
        "Follow the latest memes, announcements, and community updates in real-time.",
      teleDesc:
        "Join the core CTO community. Degens only. 24/7 energy. No sleep.",
      hubDesc:
        "Participate in discussions, governance, meme battles, and daily votes.",
      follow: "Follow",
      joinChat: "Join Chat",
      joinHub: "Join Hub",
      activityTitle: "Community Activity",
      refresh: "Refreshes every 30s",
      live: "LIVE",
      volume: "Volume 24h",
      txns: "Transactions",
      xposts: "X Posts Today",
      members: "Active Members",
      poweredBy: "Powered by",
    },
    events: {
      eyebrow: "Community · Challenges",
      heading: "Events &",
      headingAccent: "Challenges",
      sub: "Real activities, real energy. The gorilla army shows up everywhere.",
      event1Title: "Kiyomasa Challenge 🦍",
      event1Desc: "Community-driven challenge showcasing the gorilla spirit.",
      event2Title: "Community Event 🎌",
      event2Desc: "KIYOMASA community gathering and celebration.",
    },
    donation: {
      eyebrow: "Real Impact · Real Gorillas",
      heading: "Donation",
      headingAccent: "Report",
      sub: "KIYOMASA believes in giving back. A portion of community revenue is donated to real gorillas and animals in need. Every transaction is transparent and verifiable on-chain.",
      missionTitle: "Our Mission",
      missionDesc:
        "We are more than a meme. KIYOMASA stands for real gorillas — endangered, displaced, and in need of care. Together, we make a difference.",
      donationNo: "Donation #",
      recipient: "Recipient",
      verifiedOnChain: "Verified On-Chain",
      viewTx: "View Transaction →",
      proofLabel: "Proof of Donation",
      moreComingSoon:
        "More donations coming as the community grows. Every pump, every hold — it all adds up. 🦍",
      donation1: {
        title: "Donation to Grace 🦍",
        recipient: "Grace — Gorilla in Need",
        date: "June 2026",
        note: "First official KIYOMASA donation. Supporting Grace and gorilla welfare initiatives.",
      },
      donation2: {
        title: "Direct to Higashiyama Zoo 🏯",
        recipient: "Higashiyama Zoo & Botanical Gardens",
        date: "June 2026",
        note: "Direct donation to Higashiyama Zoo — the home of Kiyomasa, Japan's iconic gorilla. Supporting gorilla care and conservation programs at the zoo.",
      },
      proofImages: "Proof Images",
    },
    fanart: {
      eyebrow: "Community Art · Fan Creations",
      heading: "FANS",
      headingAccent: "ARTS",
      sub: "The gorilla army is creative. Community-made art from believers around the world.",
      marqueeLabel: "Fans Arts Gallery",
    },
    viral: {
      eyebrow: "Going Viral · As Seen On",
      heading: "KIYOMASA",
      headingAccent: "In The Media",
      sub: "The internet can't stop watching. Kiyomasa is making waves across every platform.",
      watchBtn: "Watch Now →",
      youtube: "YouTube",
      instagram: "Instagram Reel",
      twitter: "X · Twitter",
    },
    footer: {
      tagline:
        "Japan's gorilla meme movement. Community-driven. Built by believers. Powered by memes.",
      navLabel: "Navigation",
      communityLabel: "Community",
      disclaimer: "Not financial advice.",
      dyor: "DYOR.",
      copyright:
        "© 2026 KIYOMASA MEME. Built by the community. Powered by memes. 🦍🇯🇵",
    },
    music: {
      playing: "♪ PLAYING",
      bgm: "BGM",
    },
  },

  /* ── JAPANESE ── */
  ja: {
    nav: {
      home: "ホーム",
      token: "トークン",
      pump: "ポンプ",
      calculator: "計算機",
      roadmap: "ロードマップ",
      community: "コミュニティ",
      events: "イベント",
      donation: "寄付レポート",
      docs: "ドキュメント",
      buy: "$KIYOMASA を買う",
    },
    hero: {
      badge: "Solana にて稼働中",
      line1: "日本の",
      line2: "ゴリラ",
      line3: "ミームが来た",
      sub: "日本の伝説のゴリラ、清正にインスパイアされた、コミュニティ主導のミームムーブメント。",
      buyBtn: "🔥 $KIYOMASA を買う",
      joinBtn: "コミュニティに参加 🦍",
      copy: "コピー",
      network: "ネットワーク",
      supply: "供給量",
      tax: "税金",
      community: "コミュニティ",
      tapMe: "タップして！",
      clicks: "クリック",
    },
    token: {
      eyebrow: "オンチェーン · リアルタイム",
      heading: "トークン",
      headingAccent: "情報",
      price: "$KIYOMASA 価格",
      marketCap: "時価総額",
      volume24h: "24h 取引量",
      liquidity: "流動性",
      fdv: "FDV",
      buys: "買い",
      sells: "売り",
      txTotal: "24h トランザクション · 合計 {n}",
      chartLabel: "📈 リアルタイムチャート",
      openFull: "全画面で開く →",
      detailsHeading: "トークン詳細",
      caHeading: "コントラクトアドレス",
      caLabel: "Solana CA",
      copyBtn: "アドレスをコピー",
      copyOk: "✓ コピー完了！",
      buyJup: "Jupiter で購入",
      dex: "DexScreener",
      updatedJustNow: "たった今",
      updatedAgo: "{n}秒前",
      updated: "更新",
      live: "ライブ",
      buyPct: "買い {n}%",
      sellPct: "売り {n}%",
    },
    pump: {
      eyebrow: "リアルタイム · オンチェーン",
      heading: "ポンプ",
      headingAccent: "メーター",
      sub: "買い圧力・取引量・価格モメンタムの複合スコア。30秒ごとに更新。",
      score: "ポンプスコア",
      verdict: "判定",
      buy: "買い",
      sell: "売り",
      volume: "24h 取引量",
      liquidity: "流動性",
      marketCap: "時価総額",
      price1h: "1h 価格変動",
      price24h: "24h 価格変動",
      txns: "24h トランザクション",
      rekt: "全滅 💀",
      bearish: "弱気 🐻",
      neutral: "中立 😐",
      bullish: "強気 🔥",
      pumping: "急騰中 🚀",
      moon: "月まで行く 🌙",
    },
    calc: {
      eyebrow: "夢を大きく · WAGMI",
      heading: "いつ",
      headingAccent: "月行き？",
      sub: "保有枚数を入力して目標を選び、あなたの未来を見よう。",
      currentPrice: "現在価格",
      token: "トークン",
      amountLabel: "$KIYOMASA を何枚持っていますか？",
      placeholder: "例：1000000",
      multLabel: "目標倍率",
      custom: "カスタム",
      calcBtn: "🔮 ムーンバッグを計算",
      currentVal: "現在の価値",
      targetAt: "{n}x 目標時",
      profit: "利益",
      targetPrice: "目標価格",
      targetSub: "現在の{n}倍",
      disclaimer: "金融アドバイスではありません。自己責任でどうぞ。🦍",
      loading: "読み込み中…",
      wagmi: [
        "ほぼ横ばいですね 😴 もっとガチホして！",
        "なかなかいい利益。WAGMI 🤝",
        "かなり強い。勝ち組確定 🔥",
        "爆益！将来の億り人候補 🤑",
        "キヨマサ月へGO！！！🚀🌙 売ったら後悔するぞ",
      ],
    },
    community: {
      eyebrow: "ゴリラ軍団",
      heading: "ムーブメントに",
      headingAccent: "参加せよ",
      sub: "ゴリラ軍団は日に日に強くなっている。チャンネルを選んで、エネルギーを持ち込め。",
      xDesc:
        "最新のミーム、お知らせ、コミュニティ情報をリアルタイムでフォロー。",
      teleDesc:
        "CTOコアコミュニティに参加。デジェンのみ。24/7 エナジー。眠らない。",
      hubDesc: "議論、ガバナンス、ミームバトル、日々の投票に参加。",
      follow: "フォロー",
      joinChat: "チャットに参加",
      joinHub: "ハブに参加",
      activityTitle: "コミュニティ活動",
      refresh: "30秒ごとに更新",
      live: "ライブ",
      volume: "24h 取引量",
      txns: "トランザクション",
      xposts: "今日のXポスト",
      members: "アクティブメンバー",
      poweredBy: "提供：",
    },
    events: {
      eyebrow: "コミュニティ · チャレンジ",
      heading: "イベント &",
      headingAccent: "チャレンジ",
      sub: "リアルな活動、リアルなエネルギー。ゴリラ軍団はどこにでも現れる。",
      event1Title: "キヨマサ・チャレンジ 🦍",
      event1Desc: "ゴリラ精神を発揮するコミュニティ主導のチャレンジ。",
      event2Title: "コミュニティイベント 🎌",
      event2Desc: "KIYOMASAコミュニティの集いと祝典。",
    },
    donation: {
      eyebrow: "リアルな影響 · リアルなゴリラ",
      heading: "寄付",
      headingAccent: "レポート",
      sub: "KIYOMASAはお返しを信じています。コミュニティ収益の一部は、本物のゴリラや困っている動物たちに寄付されます。すべての取引は透明でオンチェーンで確認できます。",
      missionTitle: "私たちのミッション",
      missionDesc:
        "私たちはただのミームではありません。KIYOMASAは絶滅危惧種であり、居場所を失い、ケアを必要とするリアルなゴリラのために立ち上がります。",
      donationNo: "寄付 #",
      recipient: "受取人",
      verifiedOnChain: "オンチェーンで確認済み",
      viewTx: "トランザクションを見る →",
      proofLabel: "寄付証明",
      moreComingSoon:
        "コミュニティが成長するにつれ、さらなる寄付が予定されています。🦍",
      donation1: {
        title: "グレースへの寄付 🦍",
        recipient: "グレース — 助けを必要とするゴリラ",
        date: "2026年6月",
        note: "KIYOMASAの初めての公式寄付。グレースとゴリラ保護活動を支援。",
      },
      donation2: {
        title: "東山動植物園への直接寄付 🏯",
        recipient: "東山動植物園",
        date: "2026年6月",
        note: "キヨマサの故郷・東山動植物園への直接寄付。ゴリラのケアと保護プログラムを支援します。",
      },
      proofImages: "証明写真",
    },
    fanart: {
      eyebrow: "コミュニティアート · ファン作品",
      heading: "FANS",
      headingAccent: "ARTS",
      sub: "ゴリラ軍団はクリエイティブです。世界中の信者によるコミュニティアート。",
      marqueeLabel: "ファンアーツギャラリー",
    },
    viral: {
      eyebrow: "バイラル中 · 話題",
      heading: "KIYOMASA",
      headingAccent: "メディアで話題",
      sub: "インターネットが止まらない。キヨマサがあらゆるプラットフォームで話題沸騰中。",
      watchBtn: "今すぐ見る →",
      youtube: "YouTube",
      instagram: "Instagram リール",
      twitter: "X · Twitter",
    },
    footer: {
      tagline:
        "日本のゴリラミームムーブメント。コミュニティ主導。信者が作り、ミームが動かす。",
      navLabel: "ナビゲーション",
      communityLabel: "コミュニティ",
      disclaimer: "金融アドバイスではありません。",
      dyor: "自己責任で。",
      copyright:
        "© 2026 KIYOMASA MEME. コミュニティが作り、ミームが動かす。🦍🇯🇵",
    },
    music: {
      playing: "♪ 再生中",
      bgm: "BGM",
    },
  },

  /* ── CHINESE (SIMPLIFIED) ── */
  zh: {
    nav: {
      home: "首页",
      token: "代币",
      pump: "暴涨表",
      calculator: "计算器",
      roadmap: "路线图",
      community: "社区",
      events: "活动",
      donation: "捐款报告",
      docs: "文档",
      buy: "购买 $KIYOMASA",
    },
    hero: {
      badge: "Solana 实时上线",
      line1: "日本的",
      line2: "大猩猩",
      line3: "表情包来了",
      sub: "灵感来源于日本传奇大猩猩清正。由信仰者、创作者和 degen 共同建立的社区驱动表情包运动。",
      buyBtn: "🔥 购买 $KIYOMASA",
      joinBtn: "加入社区 🦍",
      copy: "复制",
      network: "网络",
      supply: "总供应量",
      tax: "税费",
      community: "社区",
      tapMe: "点我！",
      clicks: "次点击",
    },
    token: {
      eyebrow: "链上 · 实时数据",
      heading: "代币",
      headingAccent: "信息",
      price: "$KIYOMASA 价格",
      marketCap: "市值",
      volume24h: "24h 交易量",
      liquidity: "流动性",
      fdv: "完全稀释估值",
      buys: "买入",
      sells: "卖出",
      txTotal: "24h 交易笔数 · 共 {n} 笔",
      chartLabel: "📈 实时图表",
      openFull: "查看完整图表 →",
      detailsHeading: "代币详情",
      caHeading: "合约地址",
      caLabel: "Solana CA",
      copyBtn: "复制合约地址",
      copyOk: "✓ 已复制！",
      buyJup: "在 Jupiter 购买",
      dex: "DexScreener",
      updatedJustNow: "刚刚",
      updatedAgo: "{n}秒前",
      updated: "已更新",
      live: "实时",
      buyPct: "买入 {n}%",
      sellPct: "卖出 {n}%",
    },
    pump: {
      eyebrow: "实时 · 链上数据",
      heading: "暴涨",
      headingAccent: "指标",
      sub: "综合买入压力、交易量和价格动能的综合评分。每30秒更新一次。",
      score: "暴涨评分",
      verdict: "判断",
      buy: "买入",
      sell: "卖出",
      volume: "24h 交易量",
      liquidity: "流动性",
      marketCap: "市值",
      price1h: "1小时价格",
      price24h: "24小时价格",
      txns: "24h 交易笔数",
      rekt: "爆仓 💀",
      bearish: "看跌 🐻",
      neutral: "中性 😐",
      bullish: "看涨 🔥",
      pumping: "急涨中 🚀",
      moon: "冲上月球 🌙",
    },
    calc: {
      eyebrow: "大胆做梦 · WAGMI",
      heading: "何时",
      headingAccent: "登月？",
      sub: "输入你的持仓量，选择目标，看看你的财富未来。",
      currentPrice: "当前价格",
      token: "代币",
      amountLabel: "你持有多少 $KIYOMASA？",
      placeholder: "例如：1000000",
      multLabel: "目标倍数",
      custom: "自定义",
      calcBtn: "🔮 计算我的月球仓位",
      currentVal: "当前价值",
      targetAt: "{n}x 目标时",
      profit: "你的利润",
      targetPrice: "目标价格",
      targetSub: "当前价格的{n}倍",
      disclaimer: "非投资建议。请自行研究。🦍",
      loading: "加载中…",
      wagmi: [
        "基本持平 😴 继续持有兄弟",
        "不错的收益。WAGMI 🤝",
        "猛！你要发财了 🔥",
        "巨额收益！未来百万富翁 🤑",
        "KIYOMASA冲上月球！！🚀🌙 现在卖出你会后悔的",
      ],
    },
    community: {
      eyebrow: "大猩猩军团",
      heading: "加入",
      headingAccent: "运动",
      sub: "大猩猩军团每天都在壮大。选择你的频道，带来你的能量。",
      xDesc: "实时关注最新表情包、公告和社区动态。",
      teleDesc:
        "加入核心 CTO 社区。只有 degen 才能加入。全天候能量。不眠不休。",
      hubDesc: "参与讨论、治理、表情包大战和每日投票。",
      follow: "关注",
      joinChat: "加入聊天",
      joinHub: "加入中心",
      activityTitle: "社区活动",
      refresh: "每30秒更新",
      live: "实时",
      volume: "24h 交易量",
      txns: "交易笔数",
      xposts: "今日X帖子",
      members: "活跃成员",
      poweredBy: "由",
    },
    events: {
      eyebrow: "社区 · 挑战",
      heading: "活动 &",
      headingAccent: "挑战",
      sub: "真实活动，真实能量。大猩猩军团无处不在。",
      event1Title: "清正挑战 🦍",
      event1Desc: "社区驱动的挑战，展现大猩猩精神。",
      event2Title: "社区活动 🎌",
      event2Desc: "KIYOMASA社区聚会与庆典。",
    },
    donation: {
      eyebrow: "真实影响 · 真实大猩猩",
      heading: "捐款",
      headingAccent: "报告",
      sub: "KIYOMASA相信回馈社会。部分社区收益将捐给真实的大猩猩和有需要的动物。每笔交易都是透明且可在链上验证的。",
      missionTitle: "我们的使命",
      missionDesc:
        "我们不仅仅是一个表情包。KIYOMASA代表真实的大猩猩——濒危的、流离失所的、需要关怀的。我们一起创造改变。",
      donationNo: "捐款 #",
      recipient: "受捐者",
      verifiedOnChain: "链上已验证",
      viewTx: "查看交易 →",
      proofLabel: "捐款证明",
      moreComingSoon: "随着社区壮大，更多捐款即将到来。🦍",
      donation1: {
        title: "捐款给格蕾丝 🦍",
        recipient: "格蕾丝 — 需要帮助的大猩猩",
        date: "2026年6月",
        note: "KIYOMASA首次官方捐款。支持格蕾丝和大猩猩保护行动。",
      },
      donation2: {
        title: "直接捐款给东山动植物园 🏯",
        recipient: "东山动植物园",
        date: "2026年6月",
        note: "直接向东山动植物园（清正的家园）捐款，支持大猩猩护理和保护项目。",
      },
      proofImages: "证明图片",
    },
    fanart: {
      eyebrow: "社区艺术 · 粉丝创作",
      heading: "FANS",
      headingAccent: "ARTS",
      sub: "大猩猩军团充满创意。来自世界各地信仰者的社区艺术作品。",
      marqueeLabel: "粉丝艺术画廊",
    },
    viral: {
      eyebrow: "病毒式传播 · 各大平台热议",
      heading: "KIYOMASA",
      headingAccent: "媒体报道",
      sub: "互联网停不下来。清正正在各个平台掀起波澜。",
      watchBtn: "立即观看 →",
      youtube: "YouTube",
      instagram: "Instagram 视频",
      twitter: "X · Twitter",
    },
    footer: {
      tagline: "日本大猩猩表情包运动。社区驱动。由信仰者建造，由表情包驱动。",
      navLabel: "导航",
      communityLabel: "社区",
      disclaimer: "非投资建议。",
      dyor: "请自行研究。",
      copyright: "© 2026 KIYOMASA MEME. 由社区建造，由表情包驱动。🦍🇯🇵",
    },
    music: {
      playing: "♪ 播放中",
      bgm: "BGM",
    },
  },
} as const;

/* ════════════════════════════════════════
   CONTEXT
════════════════════════════════════════ */
type TData = (typeof T)["en"];

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  tr: TData;
}

const Ctx = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  tr: T.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("kiyomasa_lang") as Lang | null;
    if (saved && ["en", "ja", "zh"].includes(saved)) setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("kiyomasa_lang", l);
  };

  return (
    <Ctx.Provider value={{ lang, setLang, tr: T[lang] as TData }}>
      {children}
    </Ctx.Provider>
  );
}

export const useLang = () => useContext(Ctx);
